name: Package

on:
  push:
    branches:
      - 'master'
      
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  
jobs:
  package:
    name: package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
#     - name: Update submodules
#       run: git submodule update --init
#     - name: Build contract
#       run: make all-via-docker
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        tag_name: test
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
#     - name: upload-acp-file
#       uses: actions/upload-release-asset@v1
#       with:
#         name: anyone_can_pay
#         asset_path: ${{ github.workspace }}/build/anyone_can_pay
#         asset_name: anyone_can_pay
#         upload_url: ${{ steps.create_release.outputs.upload_url }}
